name: CI Cine App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Construir Imagen Docker
      # Usamos el comando manual para evitar que use el Dockerfile del ejemplo
      run: docker build -t cine-app .

    - name: Levantar Contenedor
      run: |
        docker run -d -p 5000:5000 --name app-container cine-app
        sleep 10

    - name: Ejecutar Pruebas de Postman
      uses: matt-ball/newman-action@v2
      with:
        collection: tests/my_api_collection.json
        args: --env-var url=http://localhost:5000